import Image from "next/image";
import Head from "next/head";
import styles from '@/styles/Faq.module.css';
import EffectImage4 from './assets/home/effect4.png';
import Header from "./container/header/header";
import About from "./container/about/about";

export default function AboutPage() {
    const Data = [
        {title:'What blockchain are you using?', content:'Affiliate means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.'},
        {title:'Will there be a mobile app?', content:"ZOE™ is a simple and understated stackable shell chair with lots of personality and character that is as beautiful when seen from below as from above. The frame is discretely tucked into the chair's molded shell, and the shell's tapering thickness gives it a friendly expression."},
        {title:'When will I be able to see other collections?', content:'Affiliate means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.'},
        {title:'How will the athletes know how big of a collection I have?', content:'Affiliate means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.'},
        {title:'How can I transfer my NFT to a different wallet?', content:'Affiliate means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.'},
        {title:'Who are the artists?', content:'Affiliate means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.'}
    ];
    return (
        <>
            <Head>
                <title>About</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />    
            </Head>     
            <main className={styles.main}>
                <Header />
                <About data={Data}/>
                <Image src={EffectImage4} alt='png' className="absolute top-0 left-0 z-0" draggable='false' />    
            </main>   
        </>
    )
}
