import Head from 'next/head';
import Image from 'next/image';
//import the component
import Header from './container/header/header';
import SearchBar from './container/searchBar/searchbar';
//import the css file
import styles from '@/styles/Collections.module.css'
//import the image file
import EffectImageOne from './assets/layout/effectImage1.png';
import Footer from './container/footer/footer';
import Product from './container/collection/collection';

const Collection = () => {
    const products = [
        'assets/collection/image1.png',
        'assets/collection/image2.png',
        'assets/collection/image3.png',
        'assets/collection/image4.png',
        'assets/collection/image5.png',
        'assets/collection/image6.png',
        'assets/collection/image7.png',
        'assets/collection/image8.png'
    ];
    return (
        <>
            <Head>
                <title>Collections Page</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                {/* Effect Image */}
                <Image src={EffectImageOne} alt='png' className='absolute right-0 z-0 lg:w-1/4 w-1/3' draggable='false' />
                {/* Header Part */}
                <Header />

                {/* Search Bar Component */}
                <SearchBar />
                <Product data={products}/>
                <Footer />
            </main>
        </>
    )
}

export default Collection;