import Head from 'next/head'
import Image from 'next/image'
import Header from './container/header/header'
import EffectImage1 from './assets/home/effect1.png';
import EffectImage2 from './assets/home/effect2.png';
import EffectImage3 from './assets/home/effect3.png';
import HomeRightImage from './assets/home/home-right.png';
import HomeEffectRightImage from './assets/home/home-effect-right.png';
import styles from '@/styles/Home.module.css'
export default function Home() {
  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header />
        <div className="max-w-7xl mx-auto">
          <div className='flex block h-screen sm:pt-0 pt-12'>
            <div className='lg:w-1/2 w-full my-auto sm:text-left text-center leading-tight text-[#331B3B]'>
              <div className='2xl:w-full w-4/5 mx-auto 2xl:text-7xl lg:text-4xl sm:text-6xl text-4xl'>
                <div>
                  <span className='font-bold'>Tap mints NFTs</span>
                </div>
                <div className='mt-1'>
                  <span>on-ther-spot from</span>
                </div>
                <div className='mt-1'>
                  <span>Athlete</span> <span>to Fan</span>
                </div>
              </div>
              <div className='2xl:w-full w-4/5 mx-auto mt-5'>
                <span className='text-sm'>A new digital game-time collectable has been created</span>
              </div>
              <div className='flex 2xl:w-full w-4/5 gap-5 2xl:mt-20 sm:mt-16 mt-8 mx-auto sm:justify-start justify-center'>
                <button className={styles.homeRegisterBtn} >
                  REGISTER
                </button>
                <button className={styles.homeSignBtn}>
                  SIGN IN
                </button>
              </div>
            </div>
            <div className='lg:w-1/2 w-full my-auto relative lg:block hidden'>
              <Image src={HomeEffectRightImage} alt='png' className='absolute right-20' draggable='false' style={{ bottom: '-30px' }} />
              <div className='w-4/5 mx-auto relative'>
                <div>
                  <Image src={HomeRightImage} alt='' className='w-full relative z-10' draggable='false' />
                </div>
                <div className='flex bg-[#331B3B] p-3' style={{ borderRadius: '0px 0px 15px 15px' }}>
                  <div className='w-3/5 text-white'>
                    <div>
                      <span className='text-base font-bold'>
                        Benjamin Pedersen
                      </span>
                    </div>
                    <div>
                      <span className='text-xs	'>
                        Indy Lights Grand Prix of Indianapolis Races 1 and 2
                      </span>
                    </div>
                  </div>
                  <div className='w-2/5 text-gray-200'>
                    <div>
                      <span className='text-sm'>
                        Indianapolis Motor Speedway
                      </span>
                    </div>
                    <div>
                      <span className='text-xs'>
                        May 13th and 14th, 2022
                      </span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <Image src={EffectImage1} alt='png' className='absolute top-0 right-0 sm:w-1/4 w-1/3' draggable='false' />
        <Image src={EffectImage2} alt='png' className='absolute bottom-0 left-0' draggable='false' />
        <Image src={EffectImage3} alt='png' className='absolute bottom-0 right-0' draggable='false' />
      </main>
    </>
  )
}
