import Image from 'next/image';
import Head from 'next/head';
import EffectImage4 from './assets/home/effect4.png';
import styles from '@/styles/Privacy.module.css';
import Header from './container/header/header';
import Footer from './container/footer/footer';
import Privacy from './container/privacy/privacy';

export default function PrivacyPage() {
    const textData = [
        '● You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.',
        '● Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to SILL GROUP LLC, 221 N BROAD ST, SUITE 3A, MIDDLETOWN, DE, 19709.',
        '● Affiliate means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.',
        '● Account means a unique account created for You to access our Service or parts of our Service.',
        '● Website refers to TapMyNFT.com, accessible from https://www.TapMyNFT.com/',
        '● Service refers to the Website.',
        '● Country refers to: United States.',
        '● Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.',
        '● Third-party Social Media Service refers to any website or any social-network website through which a User can log in or create an account to use the Service.',
        '● Personal Data is any information that relates to an identified or identifiable individual.',
        '● For the purposes of the CCPA, Personal Data means any information that identifies, relates to, describes or is capable of being associated with, or could reasonably be linked, directly or indirectly, with You.',
        '● Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.',
        '● Device means any device that can access the Service such as a computer, a cell phone or a digital tablet.',
        '● Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).',
        '● Do Not Track (DNT) is a concept that has been promoted by US regulatory authorities, in particular the U.S. Federal Trade Commission (FTC), for the Internet industry to develop and implement a mechanism for allowing internet users to control the tracking of their online activities across websites.',
        "● Business, for the purpose of the CCPA (California Consumer Privacy Act), refers to the Company as the legal entity that collects Consumers' personal information and determines the purposes and means of the processing of Consumers' personal information, or on behalf of which such information is collected and that alone, or jointly with others, determines the purposes and means of the processing of consumers' personal information, that does business in the State of California.",
        '● Consumer, for the purpose of the CCPA (California Consumer Privacy Act), means a natural person who is a California resident. A resident, as defined in the law, includes (1) every individual who is in the USA for other than a temporary or transitory purpose, and (2) every individual who is domiciled in the USA who is outside the USA for a temporary or transitory purpose.</li>',
        "● Sale, for the purpose of the CCPA (California Consumer Privacy Act), means selling, renting, releasing, disclosing, disseminating, making available, transferring, or otherwise communicating orally, in writing, or by electronic or other means, a Consumer's Personal information to another business or a third party for monetary or other valuable consideration."
    ];

    const accordionData = [
        {title:'Collecting and Using Your Personal Data', content:'Affiliate means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.'},
        {title:'Your Rights under the CCPA', content:"ZOE™ is a simple and understated stackable shell chair with lots of personality and character that is as beautiful when seen from below as from above. The frame is discretely tucked into the chair's molded shell, and the shell's tapering thickness gives it a friendly expression."},
        {title:'Exercising Your CCPA Data Protection Rights', content:'Affiliate means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.'},
        {title:'Do Not Sell My Personal Information', content:'Affiliate means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.'},
        {title:'Website', content:'Affiliate means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.'},
        {title:'Mobile Devices', content:'Affiliate means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.'}
    ];
    return (
        <>
        <Head>
            <title>Privacy</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
            <Header />
            <Privacy data1={textData} data2={accordionData}/>
            <Footer />
            <Image src={EffectImage4} alt='png' className='absolute top-0 left-0 z-0' draggable='false' />
        </main>
        </>
    )
}
