import Head from 'next/head';
import Image from 'next/image';
// import component
import Header from './container/header/header';
import Signup from './container/signup/signup';
// import css file
import styles from '@/styles/Signup.module.css';
// import image file
import EffectImage2 from './assets/home/effect2.png';
import EffectImage3 from './assets/home/effect3.png';

export default function Sign() {
    const removeLogo = [
        'remove'
    ];

    return(
        <>
         <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
            <Header data={removeLogo}/>
            <Signup />
            <Image src={EffectImage2} alt='png' className='absolute bottom-0 left-0' draggable='false' />
            <Image src={EffectImage3} alt='png' className='absolute bottom-0 right-0' draggable='false' />
        </main>   
        </>
    )
}
